Helios/Helios/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', views.home, name='home'),

    url(r'', include('Icarus.urls')),
    url(r'', include('Hestia.urls')),
]

Helios/Icarus/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [



    url(r'^wr/new/$', views.WR_new, name='WR_new'),
    url(r'^WR/new/ProjID=(?P<ProjID>\d+)$', views.WR_newproj, name='WR_newproj'),
    url(r'^wr/$', views.WR_all, name='WR_all'),
    url(r'^wr/(?P<pk>\d+)/$', views.WR_detail, name='WR_detail'),
    url(r'^wr/(?P<pk>\d+)/edit$', views.WR_edit, name='WR_edit'),
    url(r'^wr/(?P<WRID>\d+)/(?P<PFID>\d+)$', views.Task_initialtasks, name='Task_initialtasks'),

    url(r'^task/$', views.Task_all, name='Task_all'),
    url(r'^task/(?P<pk>\d+)/$', views.Task_detail, name='Task_detail'),
    url(r'^task/new/WRID=(?P<WRID>\d+)$', views.Task_new, name='Task_new'),
    url(r'^task/(?P<pk>\d+)/edit$', views.Task_edit, name='Task_edit'),
    url(r'^task/(?P<pk>\d+)/delete$', views.Task_delete, name='Task_delete'),
    url(r'^task/(?P<pk>\d+)/complete$', views.Task_complete, name='Task_complete'),
    url(r'^task/(?P<pk>\d+)/sa$', views.Task_sa, name='Task_sa'),
    url(r'^task/(?P<pk>\d+)/hold$', views.Task_hold, name='Task_hold'),

    url(r'^PFC/$', views.PFC_all, name='PFC_all'),
    url(r'^PFC/new/$', views.PFC_new, name='PFC_new'),
    url(r'^PFC/(?P<pk>\d+)/$', views.PFC_detail, name='PFC_detail'),
    url(r'^PFC/(?P<pk>\d+)/edit$', views.PFC_edit, name='PFC_edit'),

    url(r'^PF/$', views.PF_all, name='PF_all'),
    url(r'^PF/new/$', views.PF_new, name='PF_new'),
    url(r'^PF/(?P<pk>\d+)/$', views.PF_detail, name='PF_detail'),
    url(r'^PF/(?P<pk>\d+)/edit$', views.PF_edit, name='PF_edit'),
    url(r'^PF/new/from=(?P<frompk>\d+)$', views.PF_newfromexisting, name='PF_newfromexisting'),

    url(r'^tt/$', views.TT_all, name='TT_all'),
    url(r'^tt/(?P<pk>\d+)/$', views.TT_detail, name='TT_detail'),
    url(r'^tt/new/PFID=(?P<PFID>\d+)$', views.TT_new, name='TT_new'),
    url(r'^tt/(?P<pk>\d+)/edit$', views.TT_edit, name='TT_edit'),

    url(r'^role/$', views.Role_all, name='Role_all'),
    url(r'^role/(?P<pk>\d+)/$', views.Role_detail, name='Role_detail'),
    url(r'^role/new/', views.Role_new, name='Role_new'),
    url(r'^role/(?P<pk>\d+)/edit$', views.Role_edit, name='Role_edit'),
    url(r'^role/export$', views.Role_exp, name='Role_exp'),
    url(r'^role/import$', views.Role_imp, name='Role_imp'),

    url(r'^inst/$', views.Inst_all, name='Inst_all'),
    url(r'^inst/(?P<pk>\d+)/$', views.Inst_detail, name='Inst_detail'),
    url(r'^inst/new/$', views.Inst_new, name='Inst_new'),
    url(r'^inst/(?P<pk>\d+)/edit$', views.Inst_edit, name='Inst_edit'),

    url(r'^col/$', views.Col_all, name='Col_all'),
    url(r'^col/(?P<pk>\d+)/$', views.Col_detail, name='Col_detail'),
    url(r'^col/new/$', views.Col_new, name='Col_new'),
    url(r'^col/new/InstID=(?P<IID>\d+)$', views.Col_newfrominst, name='Col_newfrominst'),
    url(r'^col/(?P<pk>\d+)/edit$', views.Col_edit, name='Col_edit'),

    url(r'^sch/$', views.Sch_all, name='Sch_all'),
    url(r'^sch/(?P<pk>\d+)/$', views.Sch_detail, name='Sch_detail'),
    url(r'^sch/new/$', views.Sch_new, name='Sch_new'),
    url(r'^sch/new/CID=(?P<CID>\d+)$', views.Sch_newfromcol, name='Sch_newfromcol'),
    url(r'^sch/(?P<pk>\d+)/edit$', views.Sch_edit, name='Sch_edit'),

    url(r'^crs/$', views.Crs_all, name='Crs_all'),
    url(r'^crs/(?P<pk>\d+)/$', views.Crs_detail, name='Crs_detail'),
    url(r'^crs/new/', views.Crs_new, name='Crs_new'),
    url(r'^crs/(?P<pk>\d+)/edit$', views.Crs_edit, name='Crs_edit'),

    url(r'^cvs/$', views.Cvs_all, name='Cvs_all'),
    url(r'^cvs/(?P<pk>\d+)/$', views.Cvs_detail, name='Cvs_detail'),
    url(r'^cvs/new/', views.Cvs_new, name='Cvs_new'),
    url(r'^cvs/(?P<pk>\d+)/edit$', views.Cvs_edit, name='Cvs_edit'),

    url(r'^bkst/$', views.Bkst_all, name='Bkst_all'),
    url(r'^bkst/(?P<pk>\d+)/$', views.Bkst_detail, name='Bkst_detail'),
    url(r'^bkst/new/', views.Bkst_new, name='Bkst_new'),
    url(r'^bkst/(?P<pk>\d+)/edit$', views.Bkst_edit, name='Bkst_edit'),
]

Helios/Icarus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.conf import settings

# Create your models here.
class PFCat(models.Model):
    #Generic Fields
    create_by = models.CharField(max_length=50, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)

    #Data
    name = models.CharField(max_length=50, blank=False)
    description = models.TextField()

    #Status
    selectable = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Flows(models.Model):
    FLOW_DUR = (
        ("PRM", "Permanent"),
        ("TMP", "Temporary"),
    )
    #Generic Fields
    create_by = models.CharField(max_length=50, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)

    #Data
    name = models.CharField(max_length=50, blank=False)
    description = models.TextField()

    #Status
    selectable = models.BooleanField(default=False)
    duration = models.CharField(max_length=3, choices=FLOW_DUR, default="TMP")
    fk_PFCat = models.ForeignKey('PFCat', on_delete=models.SET_NULL, blank=True, null=True)
    instigator = models.CharField(max_length=255, blank=True, null=True) #Project or process that prompted creation of this process flow.

    def __str__(self):
        return self.name
class WorkRequests(models.Model):
    REQ_STATES = (
        ("DR", "Draft"),
        ("BA", "Backlog"),
        ("RE", "Requested"),
        ("AP", "Approved"),
        ("DE", "Denied"),
        ("IP", "In Progress"),
        ("CX", "Closed - Canceled"),
        ("CC", "Closed - Complete"),
    )

    REQ_PRI = (
        ("1", "Urgent"),
        ("2", "High"),
        ("3", "Mid"),
        ("4", "Low"),
    )

    REQ_HEALTH = (
        ("G", "Green"),
        ("Y", "Yellow"),
        ("R", "Red"),
        ("C", "Critical"),
    )

    REQ_BILLING = (
        ("CAP", "Capitalized"),
        ("EXP", "Expense"),
    )
    #Generic Fields
    create_by = models.CharField(max_length=50, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)


    #Request Details
    fk_work_req = models.ForeignKey('WorkRequests', on_delete=models.SET_NULL, blank=True, null=True)
    use_parent_details = models.BooleanField(default=False)
    requestor = models.CharField(max_length=255, null=True)
    department = models.CharField(max_length=255, null=True)
    add_contacts = models.CharField(max_length=255, null=True)
    billing = models.CharField(max_length=3, choices=REQ_PRI)
    pri = models.CharField(max_length=1, choices=REQ_PRI)
    summary = models.CharField(max_length=255, blank=False)
    impacted_loc = models.TextField(blank=True, null=True)
    details = models.TextField(blank=True, null=True)

    #files field here
    date_start = models.DateTimeField(blank=True, null=True)
    date_due = models.DateTimeField(blank=True, null=True)
    date_launch = models.DateTimeField(blank=True, null=True)

    #Review
    fk_flow = models.ForeignKey('Flows', on_delete=models.SET_NULL,blank=True, null=True)
    status = models.CharField(max_length=2, choices=REQ_STATES, default="DR")
    review_notes = models.TextField(blank=True, null=True)

    #Work
    phase = models.CharField(max_length=255, null=True, default='Draft')
    health = models.CharField(max_length=1, choices=REQ_HEALTH, default="G")
    pwa = models.CharField(max_length=255, null=True)
    fk_courseversion = models.ForeignKey('CourseVersions', on_delete=models.SET_NULL,blank=True, null=True)
    progress_notes = models.TextField(blank=True, null=True)
    date_closed = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.summary

class Roles(models.Model):
    name = models.CharField(max_length=50, blank=False)
    acronym = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return self.name


class TaskTemplates(models.Model):
    TEMPLATE_STATUSES = (
        ("P", "Pre-Planning"),
        ("A", "Assignable"),
        ("I", "In Progress"),
        ("H", "Hold"),
        ("C", "Completed"),
        ("X", "Canceled"),
    )

    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #Order
    fk_flow = models.ForeignKey('Flows', on_delete=models.CASCADE)
    orderid = models.IntegerField(blank=False)
    trigger = models.IntegerField(blank=False)
    #Defaults
    default_status = models.CharField(max_length=1, choices=TEMPLATE_STATUSES, default='P')
    phase = models.CharField(max_length=36, blank=True, null=True)
    name = models.CharField(max_length=36, blank=False)
    role = models.ForeignKey('Roles',on_delete=models.SET_NULL,blank=True, null=True)
    self_assign = models.BooleanField(default=False)
    est_capacity = models.SmallIntegerField(blank=True, null=True)
    #Actions
    resolve_WR = models.BooleanField(default=False) #Should the completion of this task trigger the completion of the related Work Request?


    def __str__(self):
        return self.name

class Tasks(models.Model):
    STATUSES = (
        ("W", "Waiting on Previous Tasks"),
        ("P", "Pre-Planning"),
        ("A", "Assignable"),
        ("I", "In Progress"),
        ("H", "Hold"),
        ("C", "Completed"),
        ("X", "Canceled"),
    )
    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #References
    fk_work_req = models.ForeignKey('WorkRequests', on_delete=models.CASCADE, blank=True, null=True)
    fk_flow = models.ForeignKey('Flows', on_delete=models.SET_NULL, blank=True, null=True)
    fk_task_template = models.ForeignKey('TaskTemplates', on_delete=models.SET_NULL, blank=True, null=True)
    #Tracking
    status = models.CharField(max_length=1, choices=STATUSES, default="P")
    name = models.CharField(max_length=36, blank=False)
    role = models.ForeignKey('Roles',on_delete=models.SET_NULL, blank=True, null=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    percent_complete = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], blank=True, null=True)
    adjusted_time = models.SmallIntegerField(blank=True, null=True)

    def initiate(self):
        self.status = 'I'
        self.save()

    def hold(self):
        if self.status == 'H':
            self.status = 'I'
        else:
            self.status = 'H'
        self.save()

    def selfassign(self, user):
        self.assigned_to = user
        self.save()

    def complete(self):
        self.status = 'C'
        self.save()

    def __str__(self):
        displayname = f"WR {self.fk_work_req_id}: {self.name}"
        return displayname

class Institutions(models.Model):
    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #Data
    name = models.CharField(max_length=255, blank=False)
    acronym = models.CharField(max_length=10, blank=False)
    contact = models.CharField(max_length=254, blank=True, null=True)
    def __str__(self):
        return self.name

class Colleges(models.Model):
    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #Data
    name = models.CharField(max_length=255, blank=False)
    acronym = models.CharField(max_length=10, blank=False)
    fk_institution = models.ForeignKey('Institutions', on_delete=models.SET_NULL, blank=True, null=True)
    contact = models.CharField(max_length=254, blank=True, null=True)
    def __str__(self):
        return self.name

class Schools(models.Model):
    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #Data
    name = models.CharField(max_length=255, blank=False)
    acronym = models.CharField(max_length=10, blank=False)
    ps_code = models.CharField(max_length=5, blank=True, null=True)
    fk_college = models.ForeignKey('Colleges', on_delete=models.SET_NULL, blank=True, null=True)
    contact = models.CharField(max_length=254, blank=True, null=True)
    def __str__(self):
        return self.name

class Courses(models.Model):
    #Generic Fields
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, blank=False)
    modified_by = models.CharField(max_length=50, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    #Data
    course_id = models.CharField(max_length=10, blank=False)
    course_pre = models.CharField(max_length=255, blank=True, null=True)
    course_num = models.CharField(max_length=255, blank=True, null=True)
    date_launched = models.DateTimeField(blank=True, null=True)
    date_retired = models.DateTimeField(blank=True, null=True)

Helios/Icarus/forms.py
from django import forms

from . import models


class WR_NewForm(forms.ModelForm):

    class Meta:
        model = models.WorkRequests
        fields = ('status', 'fk_work_req', 'use_parent_details', 'requestor', 'department', 'add_contacts', 'pri', 'summary', 'impacted_loc', 'details', 'date_start', 'date_due', 'date_launch')



class WR_EditForm(forms.ModelForm):

    class Meta:
        model = models.WorkRequests
        fields = ('status', 'fk_work_req', 'use_parent_details', 'requestor', 'department', 'add_contacts', 'pri', 'summary', 'impacted_loc', 'details', 'date_start', 'date_due', 'date_launch', 'fk_flow', 'review_notes', 'phase', 'health', 'pwa', 'fk_courseversion', 'progress_notes', 'date_closed')

class Task_NewForm(forms.ModelForm):

    class Meta:
        model = models.Tasks
        fields = ('fk_work_req', 'fk_flow','fk_task_template', 'name', 'status', 'role', 'assigned_to')

class PFC_NewForm(forms.ModelForm):

    class Meta:
        model = models.PFCat
        fields = ('name', 'description', 'selectable')

class PF_NewForm(forms.ModelForm):

    class Meta:
        model = models.Flows
        fields = ('name', 'description', 'selectable', 'duration', 'instigator', 'fk_PFCat' )

class TT_NewForm(forms.ModelForm):

    class Meta:
        model = models.TaskTemplates
        fields = ('fk_flow','orderid','trigger',  'role', 'name', 'default_status', 'phase','self_assign', 'est_capacity')

class Role_NewForm(forms.ModelForm):

    class Meta:
        model = models.Roles
        fields = ('name', 'acronym')

class Inst_NewForm(forms.ModelForm):

    class Meta:
        model = models.Institutions
        fields = ('acronym', 'name')

class Col_NewForm(forms.ModelForm):

    class Meta:
        model = models.Colleges
        fields = ('fk_institution', 'acronym','name', 'fk_institution' )

class Sch_NewForm(forms.ModelForm):

    class Meta:
        model = models.Schools
        fields = ('fk_college', 'acronym','name', 'fk_college')

class Crs_NewForm(forms.ModelForm):

    class Meta:
        model = models.Courses
        fields = ('fk_school', 'course_id', 'course_pre','course_num')

class Cvs_NewForm(forms.ModelForm):

    class Meta:
        model = models.CourseVersions
        fields = ('fk_course', 'name', 'authsys_vers', 'courseroom_temp')

class Bkst_NewForm(forms.ModelForm):

    class Meta:
        model = models.BookstoreGroups
        fields = ('code', 'name')

Helios/Icarus/templates/Icarus/PF/PF_all.html
{% extends 'Helios/base.html' %}

{% block content %}
        <h1>Icarus - All Process Flows

          <a href="{% url 'PF_new' %}">
              <button type="button" class="btn btn-outline-primary btn-sm">Create a new Process Flow</button>
          </a>
        </h1>
        <table class="table table-striped PFs">
          <thead class="black">
            <tr>
              <th>PFID</th>
              <th>Name</th>
          </thead>
          <tbody>
            {% for ProcessFlow in ProcessFlows %}
            <tr>
              <td>{{ ProcessFlow.pk }} </td>
              <td><a href="{% url 'PF_detail' pk=ProcessFlow.pk %}">{{ ProcessFlow.name }}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
{% endblock %}

Helios/Icarus/templates/Icarus/PF/PF_detail.html
{% extends 'Helios/base.html' %}

{% block content %}
        <h1>Icarus - Process Flow: {{ ProcessFlow.pk }}
        <a href="{% url 'PF_edit' pk=ProcessFlow.pk %}">
          <button type="button" class="btn btn-outline-primary btn-sm">Edit</button>
        </a>
        <a href="{% url 'PF_newfromexisting' frompk=ProcessFlow.pk %}">
          <button type="button" class="btn btn-outline-primary btn-sm">New Process Flow from this</button>
        </a>
      </h1>
        <ul>
          <li><strong>PFID:</strong> {{ ProcessFlow.pk }}</li>
          <li><strong>Name:</strong> {{ ProcessFlow.name }}</li>
          <li><strong>Description:</strong> {{ ProcessFlow.description }}</li>
        </ul>

        <h2>Related Task Templates
          <a href="{% url 'TT_new' ProcessFlow.pk %}">
            <button type="button" class="btn btn-outline-primary btn-sm">New</button>
          </a>
        </h2>
        <table class="table table-striped TTs">
          <thead class="black">
            <tr>
              <th>Order</th>
              <th>Name</th>
              <th>Role</th>
              <th>Trigger</th>
              <th>Status When Activated</th>
              <th>WR Phase When Activated</th>
              <th>Edit</th>
          </thead>
          <tbody>
            {% for tasktemplate in tasktemplates %}
            <tr>
              <td>{{ tasktemplate.orderid }}</td>
              <td><a href="{% url 'TT_detail' pk=tasktemplate.pk %}">{{ tasktemplate.name }}</a></td>
              <td>{{ tasktemplate.role }}</td>
              <td>{{ tasktemplate.trigger }}</td>
              <td>{{ tasktemplate.get_default_status_display }}</td>
              <td>{{ tasktemplate.phase }}</td>
              <td><a href="{% url 'TT_edit' tasktemplate.pk %}?returnto={{ request.path|urlencode }}">
                <button type="button" class="btn btn-outline-primary btn-sm">Edit</button>
              </a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
{% endblock %}

Helios/Icarus/templates/Icarus/PF/PF_edit.html
{% extends 'Helios/base.html' %}

{% block content %}
<h1>Edit Process Flow</h1>
<form method="POST" class="post-form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

Helios/Icarus/templates/Icarus/PF/PF_new.html
{% extends 'Helios/base.html' %}
{% block content %}
<h1>New Process Flow
{% if frompk %}
 from existing PF
{% endif %}
</h1>

{% if errormsg %}
ERROR: {{ errormsg }}
{% endif %}

<form method="POST" class="post-form" action="{% url 'users_new' %}">
  {% csrf_token %}
    <div class="row">

      <div class="col-4">
        <div class="form-group">
          <label for="pfcat">Category</label>
          <input type="text" class="form-control" id="pfcat" name="pfcat" aria-describedby="pfcatHelp" placeholder="Enter Category" value="{{ pfcat }}" />
        </div>
      </div>
      <div class="col-2">
        <div class="form-group">
          <label for="duration">Duration</label>
          <input type="text" class="form-control" id="duration" name="duration" aria-describedby="durationHelp" placeholder="Enter duration" value="{{ duration }}" />
        </div>
      </div>
      <div class="col-2">
        <div class="form-group">
          <label for="selectable">Selectable</label>
          <input type="checkbox" class="form-control" id="selectable" name="selectable" aria-describedby="selectableHelp" value="{{ selectable }}" />
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-8">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="Enter name" value="{{ name }}" />
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-8">
        <div class="form-group">
          <label for="description">Description</label>
          <input type="text" class="form-control" id="description" name="description" aria-describedby="descriptionHelp" placeholder="Enter description" value="{{ description }}" />
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-8">
        <div class="form-group">
          <label for="instigator">Instigator</label>
          <input type="text" class="form-control" id="instigator" name="instigator" aria-describedby="instigatorHelp" placeholder="Enter instigator" value="{{ instigator }}" />
        </div>
      </div>
    </div>

  <button type="submit" class="save btn btn-default">Save</button>
</form>

{% endblock %}